site_name: EPITA - Documentation
theme: readthedocs
repo_url: https://github.com/cri-epita/epita-doc/
pages:
  - Accueil: 'index.md'
  - Documentation:
    - Mots de passe: 'passwords.md'
    - 'news.md'
    - 'netsoul.md'
  - Procédures:
    - Changement de mot de passe: 'change_password.md'
    - 'redump.md'
    - Connexion à iit-wifi sous Windows: 'iit-wifi_windows.md'
  - Contact:  'contact.md'
